# Generated by Django 4.2.1 on 2023-06-30 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_categoria_date_creation_categoria_date_update_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='birthday',
            new_name='date_birthday',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='sexo',
            new_name='gender',
        ),
    ]
